language: python

python:
- '2.7'

install:
- pip install -r requirements_test.txt
- pip install .

script: python run_tests.py

before_install:
- openssl aes-256-cbc -K $encrypted_6c986365052b_key -iv $encrypted_6c986365052b_iv
  -in misc/key/test.key.enc -out misc/key/test.key -d
